# Generated by Django 4.2.11 on 2024-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_mobile', models.CharField(max_length=13)),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
    ]
